
<div data-placeholder="cart-popup" style="display: none;" class="cart-popup-class">
    <div data-bind="scope: 'cartPopup'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
{
   "*": {
       "Magento_Ui/js/core/app": {
          "components": {
               "cartPopup": {
                   "component": "Yuronn_AddToCartPopup/js/view",
                   "template": "Yuronn_AddToCartPopup/popup",
		           "productData": {
		                "productName" : "testName",
		                "productQty" : "10",
		                "productSku" : "1234567890",
		                "productPrice" : "580"
		           }
               }
           }
       }
   }
}
</script>
