<?php
/**
* @var \Magento\Framework\View\Element\Template $block
* @var \Magento\Framework\Escaper $escaper
* @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
*/
?>

<div id="km-todo" data-bind="scope: 'km-todo-scope'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#km-todo": {
                "Magento_Ui/js/core/app" : {
                    "components" : {
                        "km-todo-scope": {
                            "component": "Elogic_ToDoListKo/js/view/todo",
                            "config": {
                                "todos": [
                                    {
                                        "id": 1,
                                        "title": "Meetings",
                                        "description": "Attend daily meetings and discuss the agenda.",
                                        "start_date": "10 Mar",
                                        "end_date": "15 Mar",
                                        "completed_tasks": 5,
                                        "total_tasks": 10
                                    },
                                    {
                                        "id": 2,
                                        "title": "Meetings",
                                        "description": "Attend daily meetings and discuss the agenda.",
                                        "start_date": "10 Mar",
                                        "end_date": "19 Mar",
                                        "completed_tasks": 6,
                                        "total_tasks": 11
                                    },
                                    {
                                        "id": 3,
                                        "title": "Meetings",
                                        "description": "Attend daily meetings and discuss the agenda.",
                                        "start_date": "10 Mar",
                                        "end_date": "26 Mar",
                                        "completed_tasks": 3,
                                        "total_tasks": 7
                                    },
                                    {
                                        "id": 4,
                                        "title": "Deployment",
                                        "description": "Deployment process",
                                        "start_date": "18 Mar",
                                        "end_date": "30 Mar",
                                        "completed_tasks": 8,
                                        "total_tasks": 12
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        }
    </script>
</div>

