<?php
/**
* @var \Magento\Framework\View\Element\Template $block
* @var \Magento\Framework\Escaper $escaper
* @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
*/
?>

<div id="km-todo" data-bind="scope: 'km-todo-scope'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#km-todo": {
                "Magento_Ui/js/core/app" : <?= $block->getJsLayout(); ?>
            }
        }
    </script>
</div>

